### ISSUE TITLE
Button and typography styles

### ISSUE THREAD

**Issue by RyanWarner** [CosmosContracts/juno-tools#4]
## Tasks

- [x] remove unused stylesheets
- [x] remove unused font families
- [x] remove dark mode (since figma spec has one color mode/scheme)
- [ ] sync button styles
- [x] sync typography styles

## Links

- https://www.figma.com/file/ajr8SLkAaA08upoIMp6bds/Juno_V1?node-id=60%3A7

## Screenshots

**Button style**

![image](https://user-images.githubusercontent.com/1595979/152852421-c043bb0f-3ab7-4e35-8ef1-c7db4aa0ab0c.png)

**Comment by RyanWarner** [comment]
@grikomsn Please check figma for latest button styling, the above screenshot is out of date.
